### ISSUE TITLE
Idea: inform when publishing the same twice

### ISSUE THREAD

**Issue by webpro** [stackblitz-labs/pkg.pr.new#140]
Since the example/template has `on: [push, pull_request]` the job also runs on tags, resulting in two seemingly identical publishes for the same commit sha:

- https://github.com/webpro-nl/knip/actions/runs/9845618105/job/27181520125#step:6:14
- https://github.com/webpro-nl/knip/actions/runs/9845618200/job/27181519355#step:6:14

Nothing wrong here, but maybe nice to info/warn something like "this version was already published".

In the same vein, the Action template could be updated to something like this:

```
on:
  pull_request:
  push:
    branches:
      - '**'
    tags:
      - '!**'
```

Tags are usually published to npm anyway. Each push would still be published, though.

**Comment by webpro** [comment]
As much as I'd love to help out, I have more projects on my plate atm.

**Comment by Aslemammad** [comment]
For sure mate, will sort it out for you!

**Comment by Aslemammad** [comment]
Just sorted this out, will have a release soon!

**Comment by webpro** [comment]
Thank you! Couldn't wish for more 😊

**Comment by David-Pena** [comment]
Hi @Aslemammad @webpro I have a question about the implementation of this ⬆️

if I have this 
```
on:
  push:
    branches: 
      - main
  pull_request:
    types: [closed]
    branches: 
      - main
```

Whats suggested in this issue is that I update the template to this ⬇️ ?
```
on:
  push:
    branches: 
      - '**'
    tags
      - '!**'
  pull_request:
    types: [closed]
    branches: 
      - '**'
    tags
      - '!**'
```

I know it might be a silly question but its for an OSS repo so I wouldnt want to suggest something wrong 👀
