### ISSUE TITLE
Expose context to `GITHUB_OUTPUT`

### ISSUE THREAD

**Issue by cometkim** [stackblitz-labs/pkg.pr.new#363]
Assume a workflow that runs the e2e tests right after pkg-pr-new publish.

Package tags seem to be determined by ref or commit sha on the execution context, but the workflow does not know it.

Simply exposing some context to `GITHUB_OUTPUT` will be super helpful in making a composite workflow. E.g.

```js
append(process.env.GITHUB_OUTPUT, `tag=${refOrCommit}`);
```

```yml
- name: Publish
  id: publish
  run: npx pkg-pr-new publish

- name: E2E Test
  run:
    npm i https://pkg.pr.new/my-package@${{ steps.publish.outputs.tag }}
```
